name: Update Website Screenshots

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:  # Manual trigger
  push:
    branches: [main]
    paths: ['README.md']

jobs:
  screenshot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install Playwright
      run: |
        npm init -y
        npm install playwright
        npx playwright install chromium
        
    - name: Create Screenshot Script
      run: |
        cat > screenshot.js << 'EOF'
        const { chromium } = require('playwright');
        
        (async () => {
          const browser = await chromium.launch();
          const page = await browser.newPage();
          await page.setViewportSize({ width: 1200, height: 800 });
          
          // Screenshot ASCII Visualizer
          await page.goto('https://ascii.lewisgo.ing', { waitUntil: 'networkidle' });
          await page.waitForTimeout(3000);
          await page.screenshot({ path: 'images/ascii-visualizer.png' });
          
          // Screenshot Dithering Demo
          await page.goto('https://dither.lewisgo.ing', { waitUntil: 'networkidle' });
          await page.waitForTimeout(3000);
          await page.screenshot({ path: 'images/dithering-demo.png' });
          
          // Screenshot Music Player
          await page.goto('https://player.lewisgo.ing', { waitUntil: 'networkidle' });
          await page.waitForTimeout(3000);
          await page.screenshot({ path: 'images/music-player.png' });
          
          await browser.close();
        })();
        EOF
        
    - name: Take Screenshots
      run: |
        mkdir -p images
        node screenshot.js
          
    - name: Optimize Images
      run: |
        # Install imagemin-cli for optimization
        npm install -g imagemin-cli imagemin-pngquant
        
        # Optimize screenshots
        imagemin images/*.png --out-dir=images --plugin=pngquant
        
    - name: Commit Screenshots
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add images/
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update website screenshots 📸
          
          🤖 Generated with [Claude Code](https://claude.ai/code)
          
          Co-Authored-By: Claude <noreply@anthropic.com>"
          git push
        fi